---

version: "3.9"

services:
  example:
    build: .
    volumes:
      - ../../..:/code
      - node_modules:/code/src/examples/typescript/node_modules/
    working_dir: /code/src/examples/typescript
    command: bash -l

volumes:
  node_modules:
